/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import views.animal.MenuAnimal;
import views.users.MenuUsers;
import views.visits.MenuVisits;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Menu() {
        initComponents();
        this.setTitle("Zoologico");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsers = new javax.swing.JLabel();
        btnVisits = new javax.swing.JLabel();
        btnAnimals = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnUsers.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_users.png"))); // NOI18N
        btnUsers.setText("EMPLEADOS");
        btnUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsers.setPreferredSize(new java.awt.Dimension(150, 150));
        btnUsers.setSize(new java.awt.Dimension(150, 150));
        btnUsers.setVerifyInputWhenFocusTarget(false);
        btnUsers.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsersMousePressed(evt);
            }
        });

        btnVisits.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnVisits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVisits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_bus.png"))); // NOI18N
        btnVisits.setText("VISITANTES");
        btnVisits.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVisits.setPreferredSize(new java.awt.Dimension(150, 150));
        btnVisits.setSize(new java.awt.Dimension(150, 150));
        btnVisits.setVerifyInputWhenFocusTarget(false);
        btnVisits.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnVisits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVisitsMousePressed(evt);
            }
        });

        btnAnimals.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnAnimals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnimals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_animal.png"))); // NOI18N
        btnAnimals.setText("ANIMALES");
        btnAnimals.setToolTipText("");
        btnAnimals.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnimals.setPreferredSize(new java.awt.Dimension(150, 150));
        btnAnimals.setSize(new java.awt.Dimension(150, 150));
        btnAnimals.setVerifyInputWhenFocusTarget(false);
        btnAnimals.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAnimals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnimalsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuUsers reg = new MenuUsers();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUsersMousePressed

    private void btnAnimalsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnimalsMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuAnimal reg = new MenuAnimal();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAnimalsMousePressed

    private void btnVisitsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisitsMousePressed
        // TODO add your handling code here:
       this.setVisible(false);
        MenuVisits reg = new MenuVisits();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVisitsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnimals;
    private javax.swing.JLabel btnUsers;
    private javax.swing.JLabel btnVisits;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
