/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import code.MethodsSQL;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import view.admin.MenuAdmin;
import view.user.MenuUser;


/**
 *
 * @author Restf
 */
public class ModifyUser extends javax.swing.JFrame {
    
    MethodsSQL methodsSql = new MethodsSQL();
    ImageIcon green = new ImageIcon(getClass().getResource("/resource/Check-True.png"));
    ImageIcon red = new ImageIcon(getClass().getResource("/resource/Check-False.png"));
    private boolean check1, check2, check3, check4, check5;
    
    public ModifyUser() {
        initComponents();
        setLocationRelativeTo(null);
        String STATE = null;
        if(Login.userEntity.getState()==1){
            STATE = "Administrador";
            txtStateNew.setText(STATE);   
        } else {
            STATE = "Usuario"; 
            txtStateNew.setText(STATE);
        }
        setTitle("Car Agency - Editar datos de "+STATE+" - [ "+Login.userEntity.getName()+" ]");
        txtId.setText(Integer.toString(Login.userEntity.getId()));
        txtState.setText(STATE);
        txtName.setText(Login.userEntity.getName());
        txtEmail.setText(Login.userEntity.getEmail());
        txtRFC.setText(Login.userEntity.getRfc());
        txtUser.setText(Login.userEntity.getUser());
        txtPass.setText(Login.userEntity.getPass());
        txtAge.setText(Login.userEntity.getAge());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtIdNew = new javax.swing.JTextField();
        txtStateNew = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNameNew = new javax.swing.JTextField();
        txtEmailNew = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtUserNew = new javax.swing.JTextField();
        txtPassNew = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRFCNew = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAgeNew = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconUserExist = new javax.swing.JLabel();
        iconUserCharacter = new javax.swing.JLabel();
        UserLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        iconRFCExist = new javax.swing.JLabel();
        iconRFCChracter = new javax.swing.JLabel();
        iconEmailValidate = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        UserLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(128, 153, 155));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/back.png"))); // NOI18N
        jLabel4.setText("VOLVER");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(6, 6, 174, 66);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/MenuAdmin-edit-on.png"))); // NOI18N
        jLabel1.setText("EDITAR DATOS DE USUARIO");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(299, 14, 641, 134);

        jPanel2.setBackground(new java.awt.Color(128, 153, 155));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS ACTUALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setEnabled(false);
        txtId.setPreferredSize(new java.awt.Dimension(220, 40));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        txtState.setBackground(new java.awt.Color(255, 255, 255));
        txtState.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtState.setForeground(new java.awt.Color(51, 51, 51));
        txtState.setEnabled(false);
        txtState.setPreferredSize(new java.awt.Dimension(220, 40));
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        txtState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStateKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ESTADO");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 51));
        txtName.setEnabled(false);
        txtName.setPreferredSize(new java.awt.Dimension(220, 40));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setEnabled(false);
        txtEmail.setPreferredSize(new java.awt.Dimension(220, 40));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CORREO");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USUARIO");

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(51, 51, 51));
        txtUser.setEnabled(false);
        txtUser.setPreferredSize(new java.awt.Dimension(220, 40));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setEnabled(false);
        txtPass.setPreferredSize(new java.awt.Dimension(220, 40));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONTRASEÑA");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EDAD");

        txtAge.setBackground(new java.awt.Color(255, 255, 255));
        txtAge.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(51, 51, 51));
        txtAge.setEnabled(false);
        txtAge.setPreferredSize(new java.awt.Dimension(220, 40));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });

        txtRFC.setBackground(new java.awt.Color(255, 255, 255));
        txtRFC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRFC.setForeground(new java.awt.Color(51, 51, 51));
        txtRFC.setEnabled(false);
        txtRFC.setPreferredSize(new java.awt.Dimension(220, 40));
        txtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCActionPerformed(evt);
            }
        });
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RFC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(70, 70, 70)
                        .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(80, 80, 80)
                        .addComponent(txtState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(338, 175, 444, 413);

        jPanel3.setBackground(new java.awt.Color(128, 153, 155));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS NUEVIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");

        txtIdNew.setBackground(new java.awt.Color(255, 255, 255));
        txtIdNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIdNew.setForeground(new java.awt.Color(51, 51, 51));
        txtIdNew.setEnabled(false);
        txtIdNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtIdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNewActionPerformed(evt);
            }
        });
        txtIdNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdNewKeyTyped(evt);
            }
        });

        txtStateNew.setBackground(new java.awt.Color(255, 255, 255));
        txtStateNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStateNew.setForeground(new java.awt.Color(51, 51, 51));
        txtStateNew.setEnabled(false);
        txtStateNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtStateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateNewActionPerformed(evt);
            }
        });
        txtStateNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStateNewKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ESTADO");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NOMBRE");

        txtNameNew.setBackground(new java.awt.Color(255, 255, 255));
        txtNameNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNameNew.setForeground(new java.awt.Color(102, 102, 102));
        txtNameNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtNameNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameNewActionPerformed(evt);
            }
        });
        txtNameNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameNewKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameNewKeyTyped(evt);
            }
        });

        txtEmailNew.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEmailNew.setForeground(new java.awt.Color(102, 102, 102));
        txtEmailNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtEmailNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailNewActionPerformed(evt);
            }
        });
        txtEmailNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailNewKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailNewKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CORREO");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("USUARIO");

        txtUserNew.setBackground(new java.awt.Color(255, 255, 255));
        txtUserNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUserNew.setForeground(new java.awt.Color(102, 102, 102));
        txtUserNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtUserNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNewActionPerformed(evt);
            }
        });
        txtUserNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNewKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNewKeyTyped(evt);
            }
        });

        txtPassNew.setBackground(new java.awt.Color(255, 255, 255));
        txtPassNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPassNew.setForeground(new java.awt.Color(102, 102, 102));
        txtPassNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtPassNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassNewActionPerformed(evt);
            }
        });
        txtPassNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassNewKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassNewKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CONTRASEÑA");

        txtRFCNew.setBackground(new java.awt.Color(255, 255, 255));
        txtRFCNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRFCNew.setForeground(new java.awt.Color(102, 102, 102));
        txtRFCNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtRFCNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCNewActionPerformed(evt);
            }
        });
        txtRFCNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFCNewKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCNewKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("RFC");

        txtAgeNew.setBackground(new java.awt.Color(255, 255, 255));
        txtAgeNew.setToolTipText("");
        txtAgeNew.setDateFormatString("yyyy-mm-dd");
        txtAgeNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAgeNew.setPreferredSize(new java.awt.Dimension(220, 40));
        txtAgeNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeNewKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeNewKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("EDAD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(113, 113, 113)
                        .addComponent(txtAgeNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRFCNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(70, 70, 70)
                                .addComponent(txtUserNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmailNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNameNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(80, 80, 80)
                                    .addComponent(txtStateNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPassNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtStateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNameNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEmailNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtRFCNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtAgeNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtUserNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPassNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(788, 175, 448, 413);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSave.setText("ACTUALIZAR");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(660, 610, 245, 68);

        jPanel5.setBackground(new java.awt.Color(128, 153, 155));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        UserLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("USUARIO");
        UserLabel.setFocusable(false);

        iconUserExist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        iconUserExist.setForeground(new java.awt.Color(255, 255, 255));
        iconUserExist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Check-False.png"))); // NOI18N
        iconUserExist.setText(" » Usuario no existente");
        iconUserExist.setFocusable(false);

        iconUserCharacter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        iconUserCharacter.setForeground(new java.awt.Color(255, 255, 255));
        iconUserCharacter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Check-False.png"))); // NOI18N
        iconUserCharacter.setText(" » Minimo 8 caracteres");
        iconUserCharacter.setFocusable(false);

        UserLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UserLabel1.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel1.setText("RFC");
        UserLabel1.setFocusable(false);

        iconRFCExist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        iconRFCExist.setForeground(new java.awt.Color(255, 255, 255));
        iconRFCExist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Check-False.png"))); // NOI18N
        iconRFCExist.setText(" » RFC no registrado");
        iconRFCExist.setFocusable(false);

        iconRFCChracter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        iconRFCChracter.setForeground(new java.awt.Color(255, 255, 255));
        iconRFCChracter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Check-False.png"))); // NOI18N
        iconRFCChracter.setText(" » Minimo 12 caracteres");
        iconRFCChracter.setFocusable(false);

        iconEmailValidate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        iconEmailValidate.setForeground(new java.awt.Color(255, 255, 255));
        iconEmailValidate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Check-False.png"))); // NOI18N
        iconEmailValidate.setText(" » Correo no valido");
        iconEmailValidate.setFocusable(false);

        UserLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UserLabel2.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel2.setText("CORREO");
        UserLabel2.setFocusable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconUserExist, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconUserCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel1)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconRFCExist, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconRFCChracter, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(UserLabel2))
                    .addComponent(iconEmailValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserLabel)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iconUserExist))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(iconUserCharacter)
                .addGap(18, 18, 18)
                .addComponent(UserLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iconRFCExist))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(iconRFCChracter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserLabel2)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iconEmailValidate))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(25, 249, 307, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        if (Login.userEntity.getState() == 1) {
            MenuAdmin menu = new MenuAdmin();
            menu.setVisible(true); }
        if (Login.userEntity.getState() == 0) {
            MenuUser menu = new MenuUser();
            menu.setVisible(true); }       
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
    
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtStateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateKeyTyped

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassKeyTyped

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtIdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdNewActionPerformed

    private void txtIdNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdNewKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdNewKeyTyped

    private void txtStateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateNewActionPerformed

    private void txtStateNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStateNewKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateNewKeyTyped

    private void txtNameNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameNewActionPerformed

    private void txtNameNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameNewKeyTyped
        if(txtNameNew.getText().length()>=25) evt.consume();
    }//GEN-LAST:event_txtNameNewKeyTyped

    private void txtEmailNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailNewActionPerformed

    private void txtEmailNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailNewKeyTyped
        if(txtEmailNew.getText().length()>=25) evt.consume();
    }//GEN-LAST:event_txtEmailNewKeyTyped

    private void txtUserNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNewActionPerformed

    private void txtUserNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNewKeyTyped
        if(txtUserNew.getText().length()>=12) evt.consume();
    }//GEN-LAST:event_txtUserNewKeyTyped

    private void txtPassNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassNewActionPerformed

    private void txtPassNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassNewKeyTyped
        if(txtPassNew.getText().length()>=12) evt.consume();
    }//GEN-LAST:event_txtPassNewKeyTyped

    private void txtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCActionPerformed

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCKeyTyped

    private void txtRFCNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCNewActionPerformed

    private void txtRFCNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCNewKeyTyped
        if(txtRFCNew.getText().length()>=13) evt.consume();
    }//GEN-LAST:event_txtRFCNewKeyTyped

    private void txtAgeNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeNewKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeNewKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        validateData();
        clear();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtRFCNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCNewKeyReleased
        validateRFC();
        validateButton();
        Mayusculas(txtRFCNew);
        iconRFCExist.setForeground(Color.WHITE);
        iconRFCChracter.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtRFCNewKeyReleased

    private void txtUserNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNewKeyReleased
        validateUser();
        validateButton();
        iconUserExist.setForeground(Color.WHITE);
        iconUserCharacter.setForeground(Color.WHITE);        
    }//GEN-LAST:event_txtUserNewKeyReleased

    private void txtNameNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameNewKeyReleased
        validateButton();
    }//GEN-LAST:event_txtNameNewKeyReleased

    private void txtEmailNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailNewKeyReleased
        check5 = isEmail(txtEmailNew.getText());
        if(check5){ 
            iconEmailValidate.setIcon(green); 
            iconEmailValidate.setText("» Correo Valido");
        } else { iconEmailValidate.setIcon(red); }
        validateButton();
    }//GEN-LAST:event_txtEmailNewKeyReleased

    private void txtPassNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassNewKeyReleased
        validateButton();
    }//GEN-LAST:event_txtPassNewKeyReleased

    private void txtAgeNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeNewKeyReleased
        validateButton();
    }//GEN-LAST:event_txtAgeNewKeyReleased
    
    public void validateData(){
        String name = txtNameNew.getText();
        String email = txtEmailNew.getText();
        String rfc = txtRFCNew.getText().toUpperCase();
        String user = txtUserNew.getText().toLowerCase();
        String pass = txtPassNew.getText().toLowerCase();
        if(check1 == true && check2 == true && check3 == true && check4 == true){
            int id = (int) (Math.random()*1500+1000);
            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String age = formatter.format(txtAgeNew.getDate());
            methodsSql.ModifyUserData(Login.userEntity.getId(), name, email, rfc, user, pass, age);
            Login.userEntity = methodsSql.Login(user, pass);
            this.setVisible(false);
            MenuUser menu = new MenuUser();
            menu.setVisible(true);        
            dispose();
        } 
    }
    
    public void validateUser(){
        if(methodsSql.ValidateUser(txtUserNew.getText())){
            iconUserExist.setText(" » Usuario ya existente");
            iconUserExist.setIcon(red);
            check1 = false;
        } else {
            iconUserExist.setText(" » Usuario no existente");
            iconUserExist.setIcon(green);
            check1 = true;
        }
        if(txtUserNew.getText().length() <= 8){
            iconUserCharacter.setText(" » Minimo 8 caracteres");
            iconUserCharacter.setIcon(red);
            check2 = false;
        } else {
            iconUserCharacter.setIcon(green);
            check2 = true;
        }
        if(txtUser.getText().equals("")){
            iconUserExist.setIcon(red);
            iconUserCharacter.setIcon(red);
        }
    }
    
    public void validateRFC(){
        if(methodsSql.ValidateRFC(txtRFCNew.getText())){
            iconRFCExist.setText(" » RFC ya registrado");
            iconRFCExist.setIcon(red);
            check3 = false;
        } else {
            iconRFCExist.setText(" » RFC no registrado");
            iconRFCExist.setIcon(green);
            check3 = true;
        }
        if(txtRFCNew.getText().length() < 12){
            iconRFCChracter.setText(" » Minimo 12 caracteres");
            iconRFCChracter.setIcon(red);
            check4 = false;
        } else {
            iconRFCChracter.setIcon(green);
            check4 = true;
        }
        if(txtRFC.getText().equals("")){
            iconRFCExist.setIcon(red);
            iconRFCChracter.setIcon(red);
        }
    }
    
    public void validateButton(){
        if(txtNameNew.getText().equals("") || txtEmailNew.getText().equals("") ||
           txtRFCNew.getText() .equals("") || txtUserNew.getText() .equals("") || 
           txtPassNew.getText().equals("") || txtAgeNew.getDate() == null || 
           check1 == false || check2 == false ||
           check3 == false || check4 == false || check5 == false){
                btnSave.setEnabled(false);
        } else {
                btnSave.setEnabled(true);
        }
    }
    
    public void Mayusculas(javax.swing.JTextField jTextfieldS){
         String cadena = (txtRFCNew.getText()).toUpperCase();
         txtRFCNew.setText(cadena);
    }
    
    public boolean isEmail(String correo) {        
        Pattern pattern = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
        Matcher mather = pattern.matcher(correo);
        if(mather.find()) {
            return true;
        }else{
            return false;
        }        
    }
    
    public void clear(){
        txtIdNew.setText(null);
        txtStateNew.setText(null);
        txtNameNew.setText(null);
        txtEmailNew.setText(null);
        txtRFCNew.setText(null);
        txtUserNew.setText(null);
        txtPassNew.setText(null);
        iconUserExist.setIcon(red);
        iconUserCharacter.setIcon(red);
        iconRFCExist.setIcon(red);
        iconRFCChracter.setIcon(red);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserLabel1;
    private javax.swing.JLabel UserLabel2;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel iconEmailValidate;
    private javax.swing.JLabel iconRFCChracter;
    private javax.swing.JLabel iconRFCExist;
    private javax.swing.JLabel iconUserCharacter;
    private javax.swing.JLabel iconUserExist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtAge;
    private com.toedter.calendar.JDateChooser txtAgeNew;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailNew;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdNew;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameNew;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPassNew;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtRFCNew;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStateNew;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserNew;
    // End of variables declaration//GEN-END:variables
}
