/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import code.MethodsSQL;
import javax.swing.ImageIcon;
import view.Login;

/**
 *
 * @author Restf
 */
public class Vehicle extends javax.swing.JFrame {

    MethodsSQL methodsSql = new MethodsSQL();
    ImageIcon car  = new ImageIcon(getClass().getResource("/resource/car.png"));
    ImageIcon nissanWhite  = new ImageIcon(getClass().getResource("/resource/car-nissan-white.png"));
    ImageIcon nissanRed    = new ImageIcon(getClass().getResource("/resource/car-nissan-red.png"));
    ImageIcon nissanOrange = new ImageIcon(getClass().getResource("/resource/car-nissan-orage.png"));
    ImageIcon nissanYellow = new ImageIcon(getClass().getResource("/resource/car-nissan-yellow.png"));
    ImageIcon nissanGreen  = new ImageIcon(getClass().getResource("/resource/car-nissan-green.png"));
    ImageIcon nissanBlue   = new ImageIcon(getClass().getResource("/resource/car-nissan-blue.png"));
    ImageIcon nissanGray   = new ImageIcon(getClass().getResource("/resource/car-nissan-gray.png"));
    
    ImageIcon audiWhite  = new ImageIcon(getClass().getResource("/resource/car-audi-white.png"));
    ImageIcon audiRed    = new ImageIcon(getClass().getResource("/resource/car-audi-red.png"));
    ImageIcon audiOrange = new ImageIcon(getClass().getResource("/resource/car-audi-orage.png"));
    ImageIcon audiYellow = new ImageIcon(getClass().getResource("/resource/car-audi-yellow.png"));
    ImageIcon audiGreen  = new ImageIcon(getClass().getResource("/resource/car-audi-green.png"));
    ImageIcon audiBlue   = new ImageIcon(getClass().getResource("/resource/car-audi-blue.png"));
    ImageIcon audiGray   = new ImageIcon(getClass().getResource("/resource/car-audi-gray.png"));
    
    ImageIcon volkswagenWhite  = new ImageIcon(getClass().getResource("/resource/car-volkswagen-white.png"));
    ImageIcon volkswagenRed    = new ImageIcon(getClass().getResource("/resource/car-volkswagen-red.png"));
    ImageIcon volkswagenOrange = new ImageIcon(getClass().getResource("/resource/car-volkswagen-orage.png"));
    ImageIcon volkswagenYellow = new ImageIcon(getClass().getResource("/resource/car-volkswagen-yellow.png"));
    ImageIcon volkswagenGreen  = new ImageIcon(getClass().getResource("/resource/car-volkswagen-green.png"));
    ImageIcon volkswagenBlue   = new ImageIcon(getClass().getResource("/resource/car-volkswagen-blue.png"));
    ImageIcon volkswagenGray   = new ImageIcon(getClass().getResource("/resource/car-volkswagen-gray.png"));
    
    public Vehicle() {
        initComponents();
        setTitle("Car Agency - Vehiculos - [ "+Login.userEntity.getName()+" ]");
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectCompany = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        selectState = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        selectModel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        selectColors = new javax.swing.JComboBox<>();
        iconCar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(128, 153, 155));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/back.png"))); // NOI18N
        jLabel7.setText("VOLVER");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("► SELECCIONA LOS SIGUIENTES DATOS  ◄");
        jLabel5.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("» COMPAÑIA");
        jLabel1.setToolTipText("");

        selectCompany.setBackground(new java.awt.Color(255, 255, 255));
        selectCompany.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectCompany.setForeground(new java.awt.Color(0, 0, 0));
        selectCompany.setMaximumRowCount(4);
        selectCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "• NISSAN", "• AUDI", "• VOLKSWAGEN" }));
        selectCompany.setPreferredSize(new java.awt.Dimension(220, 40));
        selectCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCompanyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("» ESTADO");
        jLabel2.setToolTipText("");

        selectState.setBackground(new java.awt.Color(255, 255, 255));
        selectState.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectState.setForeground(new java.awt.Color(0, 0, 0));
        selectState.setMaximumRowCount(4);
        selectState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "• NUEVO", "• SEMINUEVO", "• USADO", " " }));
        selectState.setEnabled(false);
        selectState.setPreferredSize(new java.awt.Dimension(220, 40));
        selectState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("» MODELO");
        jLabel3.setToolTipText("");

        selectModel.setBackground(new java.awt.Color(255, 255, 255));
        selectModel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectModel.setForeground(new java.awt.Color(0, 0, 0));
        selectModel.setMaximumRowCount(4);
        selectModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        selectModel.setEnabled(false);
        selectModel.setPreferredSize(new java.awt.Dimension(220, 40));
        selectModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectModelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("» COLORES");
        jLabel4.setToolTipText("");

        selectColors.setBackground(new java.awt.Color(255, 255, 255));
        selectColors.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectColors.setForeground(new java.awt.Color(0, 0, 0));
        selectColors.setMaximumRowCount(4);
        selectColors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "• BLANCO", "• ROJO", "• NARANJA", "• AMARILLO", "• VERDE", "• AZUL", "• GRIS" }));
        selectColors.setEnabled(false);
        selectColors.setPreferredSize(new java.awt.Dimension(220, 40));
        selectColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectColorsActionPerformed(evt);
            }
        });

        iconCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/car.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1091, 1091, 1091)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(selectColors, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(6, 6, 6)
                                        .addComponent(selectCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(29, 29, 29)
                                        .addComponent(selectState, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(25, 25, 25)
                                        .addComponent(selectModel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconCar)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addComponent(selectCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))
                            .addComponent(selectState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3))
                            .addComponent(selectModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addComponent(selectColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(iconCar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setVisible(false);
        MenuUser menu = new MenuUser();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void selectCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCompanyActionPerformed
        if (selectCompany.getSelectedIndex() > 0) {
            selectState.setEnabled(true);
            selectState.setSelectedIndex(0);
            switch(selectCompany.getSelectedIndex()){
                case 1:
                    iconCar.setIcon(nissanWhite);
                    break;
                case 2:
                    iconCar.setIcon(audiWhite);
                    break;
                case 3:
                    iconCar.setIcon(volkswagenWhite);
                    break;
            }
        } else {
            clear();
        }
    }//GEN-LAST:event_selectCompanyActionPerformed

    private void selectStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStateActionPerformed
        if (selectState.getSelectedIndex() > 0) {
            selectModel.setEnabled(true);
            selectColors.setEnabled(false);
            selectColors.setSelectedIndex(0);
            switch(selectCompany.getSelectedIndex()){
                case 1:
                    iconCar.setIcon(nissanWhite);
                    break;
                case 2:
                    iconCar.setIcon(audiWhite);
                    break;
                case 3:
                    iconCar.setIcon(volkswagenWhite);
                    break;
            }
            selectModel.setModel(methodsSql.loadModels(selectCompany.getSelectedIndex(), selectState.getSelectedIndex()));
        } else {
            selectModel.setEnabled(false);
            selectColors.setEnabled(false);
            selectModel.setSelectedIndex(0);
            selectColors.setSelectedIndex(0);
        }
    }//GEN-LAST:event_selectStateActionPerformed

    private void selectModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectModelActionPerformed
        if (selectModel.getSelectedIndex() > 0) {
            selectColors.setEnabled(true);
            String txtmodel = selectModel.getSelectedItem().toString();
            String model = txtmodel.substring(2);
            selectColors.setModel(methodsSql.loadColorsVehicle(model));
        } else {
            selectColors.setEnabled(false);
            selectColors.setSelectedIndex(0);
        }
    }//GEN-LAST:event_selectModelActionPerformed

    private void selectColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectColorsActionPerformed
        String txtcompany = selectCompany.getSelectedItem().toString();
        String company = txtcompany.substring(2);
        String txtcolor = selectColors.getSelectedItem().toString();
        String color = txtcolor.substring(2);
        switch(company){
            case "NISSAN":
                switch(color){
                    case "BLANCO":
                        iconCar.setIcon(nissanWhite);
                        break;
                    case "ROJO":
                        iconCar.setIcon(nissanRed);
                        break;
                    case "NARANJA":
                        iconCar.setIcon(nissanOrange);
                        break;
                    case "AMARILLO":
                        iconCar.setIcon(nissanYellow);
                        break;
                    case "VERDE":
                        iconCar.setIcon(nissanGreen);
                        break;
                    case "AZUL":
                        iconCar.setIcon(nissanBlue);
                        break;
                    case "GRIS":
                        iconCar.setIcon(nissanGray);
                        break;
                }
                break;
            case "AUDI":
                switch(color){
                    case "BLANCO":
                        iconCar.setIcon(audiWhite);
                        break;
                    case "ROJO":
                        iconCar.setIcon(audiRed);
                        break;
                    case "NARANJA":
                        iconCar.setIcon(audiOrange);
                        break;
                    case "AMARILLO":
                        iconCar.setIcon(audiYellow);
                        break;
                    case "VERDE":
                        iconCar.setIcon(audiGreen);
                        break;
                    case "AZUL":
                        iconCar.setIcon(audiBlue);
                        break;
                    case "GRIS":
                        iconCar.setIcon(audiGray);
                        break;
                }
                break;
            case "VOLKSWAGEN":
                switch(color){
                    case "BLANCO":
                        iconCar.setIcon(volkswagenWhite);
                        break;
                    case "ROJO":
                        iconCar.setIcon(volkswagenRed);
                        break;
                    case "NARANJA":
                        iconCar.setIcon(volkswagenOrange);
                        break;
                    case "AMARILLO":
                        iconCar.setIcon(volkswagenYellow);
                        break;
                    case "VERDE":
                        iconCar.setIcon(volkswagenGreen);
                        break;
                    case "AZUL":
                        iconCar.setIcon(volkswagenBlue);
                        break;
                    case "GRIS":
                        iconCar.setIcon(volkswagenGray);
                        break;
                }
                break;
        }
    }//GEN-LAST:event_selectColorsActionPerformed

    private void clear(){
        selectState.setEnabled(false);
        selectModel.setEnabled(false);
        selectColors.setEnabled(false);
        selectState.setSelectedIndex(0);
        selectModel.setSelectedIndex(0);
        selectColors.setSelectedIndex(0);
        iconCar.setIcon(car);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectColors;
    private javax.swing.JComboBox<String> selectCompany;
    private javax.swing.JComboBox<String> selectModel;
    private javax.swing.JComboBox<String> selectState;
    // End of variables declaration//GEN-END:variables
}
